### ISSUE TITLE
Please consider unregistering angular-logger from bower in favor of matured original project

### ISSUE THREAD

**Issue by bbottema** [mattlo/angular-logger#1]
Hello Matt,

First, thank you for making the angular world better by releasing _angular-logger_ to bower. Someone had to do it!

As you may or may not know, angular-logger was originally based on my blog post ["Enhancing $log in AngularJs the simple way"](http://blog.projectnibble.org/2013/12/23/enhance-logging-in-angularjs-the-simple-way/). Pedro converted the code into the original [angular-logging](https://github.com/pdorgambide/angular-logger) project from which you forked and released to bower.

However, we relaunched the project and further developed it into maturity. You can find it now at: https://github.com/better-js-logging/angular-logger. There is also a specialized version to enhance [console logging](https://github.com/better-js-logging/console-logger/) instead. It is now better configurable with more flexibility, has a lot less bugs and optionally works with [sprintf](https://github.com/alexei/sprintf.js/) _and_ [momentjs](http://momentjs.com/) pattern capabilities. The code is supported by Travis build, jasmine unit tests and coverage report, Codacy and CodeClimate analyses and Coveralls support (just check the badges in the [README.md](https://github.com/better-js-logging/angular-logger/blob/master/README.md)).

We wish to register this newly updated and actively developed project under the original name "angular-logger", which is currently still in use by your version.

Will you please contribute to the Open Source and Angular space once more and let us have control of the package name "angular-logger"? You can very simply remove the registration as follows:

``` javascript
bower login // (login using GitHub credentials)
bower unregister angular-logger
```

Let me know if you run into trouble with this. Of course, also let us know if you're missing anything.
- Benny

**Comment by bbottema** [comment]
Extra note: The actual logging enhancing code was abstracted into a [separate base project](https://github.com/better-js-logging/better-logging-base) and is reused in both angular-logger and console-logger (using browserify). Now, angular-logger has _only_ the Angularjs specific code and so is much easier to maintain, test and debug).

**Comment by mattlo** [comment]
@bbottema A couple questions:
- By changing the name, any projects currently dependent on this will break due to implementation delta. I have a couple ideas in how to hack it, but what is your strategy to resolve this?
- I'm not necessarily against changing names, but I disagree my implementation was a fork variant of your post. mattlo/angular-logger is a much more trivial source and I don't see any design correlation with your old and new implementation. What are the pragmatic reasons on why we need to exercise a name change?

**Comment by bbottema** [comment]
@mattlo I do believe I owe you an apology. Based on the name and very similar code examples on your README.md I had assumed it was forked from the same original code. I did not look at the code.

However, after inspecting your code properly, my request remains unchanged.

> By changing the name, any projects currently dependent on this will break due to implementation delta. I have a couple ideas in how to hack it, but what is your strategy to resolve this?

Fair question. From what I understand of your code, it seems there is only the module dependency, correct? I feel this is a better name anyway, so our module name "logger" would change to "angular-logger". Existing users would not be affected to the point of breaking their code.

> I'm not necessarily against changing names, but I disagree my implementation was a fork variant of your post. mattlo/angular-logger is a much more trivial source and I don't see any design correlation with your old and new implementation. What are the pragmatic reasons on why we need to exercise a name change?

Correct, I understand this better now. It seems our projects try to achieve something very similar. Once we implement [#2](https://github.com/better-js-logging/angular-logger/issues/2), our angular-logger will completely include your functionality.

The only pragmatic reason is recognizability. We can ofcourse register under angular-logger with some prefix, but we prefer the 'real deal' so to speak.

**Comment by bbottema** [comment]
I just added this drop-in behavior to [better-js-logging/angular-logger](https://github.com/better-js-logging/angular-logger). Now your library's behavior is included in our angular-logger.

**Comment by bbottema** [comment]
I just added this drop-in behavior to [better-js-logging/angular-logger](https://github.com/better-js-logging/angular-logger). Now your library's behavior is included in our angular-logger (as well as an extra `.trace()` function). I also renamed the module so that it won't break any existing code.
- [simple drop-in demo](https://jsfiddle.net/plantface/b0v0s2rg/)
- [config demo](https://jsfiddle.net/plantface/6jmtf2or/)

**Comment by mattlo** [comment]
:+1: Before I make the switch, please have a release 1.0 around, then an incremented version (so `update` will trigger a re-pull, unless Bower knows when repos change). Refer to the semver release https://github.com/mattlo/angular-logger/releases

Also add a PR to update this repo's README notifying users this repo is no longer maintained and is superseded by your repo with a link. After these are satisfied, I'll gladly execute the commands mentioned above.

Thanks

-Matt

**Comment by bbottema** [comment]
@mattlo All set and done!

**Comment by bbottema** [comment]
Hello @mattlo, have you had a chance to look into this?

**Comment by mattlo** [comment]
@bbottema yup sorry, I've been busy all week. I'll work on this now.

**Comment by mattlo** [comment]
![screen shot 2015-06-13 at 12 45 02 pm](https://cloud.githubusercontent.com/assets/1714244/8145347/0e9ca15a-11ca-11e5-8d6f-d7e891eb0461.png)

**Comment by bbottema** [comment]
Package angular-logger registered successfully!
All valid semver tags on git://
github.com/better-js-logging/angular-logger.git will be available as
versions.
To publish a new version, just release a valid semver tag.

Run bower info angular-logger to list the available versions.
bbottema@angular-logger:~/workspace (master) $ git tag 1.0.1
bbottema@angular-logger:~/workspace (master) $ git push --tags
Username for 'https://github.com': bbottema
Password for 'https://bbottema@github.com':
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/better-js-logging/angular-logger
- [new tag]         1.0.1 -> 1.0.1

**Comment by bbottema** [comment]
Alright @mattlo, thank you so much. We'll keep angular-logger in good shape!
